[package]
name = "rcon"
version = "0.4.0"
authors = ["panicbit <panicbit@users.noreply.github.com>"]
description = "An rcon protocol implementation"
license = "MIT OR Apache-2.0"
keywords = ["source", "rcon", "protocol", "minecraft"]
repository = "https://github.com/panicbit/rust-rcon"
edition = "2018"

[dependencies]
err-derive = "0.3.0"
tokio = { version = "1.0.0", features = ["net", "io-util", "time", "macros"], optional = true }
async-std = { version = "1.9.0", optional = true }
bytes = "1.0.1"

[dev-dependencies]
tokio = { version = "1.0.0", features = ["rt-multi-thread", "macros"] }

[features]
default = ["runtime-tokio"]
runtime-tokio = ["tokio"]
runtime-async_std = ["async-std"]
