[package]
name = "rcon"
version = "0.3.1"
authors = ["panicbit <panicbit@users.noreply.github.com>"]
description = "An rcon protocol implementation"
license = "MIT OR Apache-2.0"
keywords = ["source", "rcon", "protocol", "minecraft"]
repository = "https://github.com/panicbit/rust-rcon"
edition = "2018"

[dependencies]
err-derive = "0.3.0"
tokio = { version = "1.0.0", features = ["net", "io-util", "time", "macros"] }

[dev-dependencies]
tokio = { version = "1.0.0", features = ["rt-multi-thread", "macros"] }

[features]
default = []
